# Use root/example as user/password credentials


version: '3.1'

services:
  mysql_cursos:
    container_name: mysql_cursos
    hostname: mysql_cursos
    image: mysql
    restart: always

    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    
    volumes:
      - C:\Users\felip\Documents\UFPB\Estudos\sql:/var/lib/mysql 
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: base_de_dados
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080